### ISSUE TITLE
circle: "undeclared identifier" in macro

### ISSUE THREAD

**Issue by jaredhoberock** [seanbaxter/circle#31]
When compiled with circle, the program:

```
#include <type_traits>

#  define CONCATENATE_IMPL(x, y) x##y

#  define CONCATENATE(x, y) CONCATENATE_IMPL(x, y)

#  define MAKE_UNIQUE(x) CONCATENATE(x, __COUNTER__)

#  define REQUIRES_IMPL(unique_name, ...) bool unique_name = true, typename std::enable_if<(unique_name and __VA_ARGS__)>::type* = nullptr

#  define REQUIRES(...) REQUIRES_IMPL(MAKE_UNIQUE(__deduced_true), __VA_ARGS__)


struct foo
{
  template<class T,
           REQUIRES(std::is_arithmetic<T>::value)
          >
  void bar();
};

int main()
{
}
```

Produces the following compilation error message:

```
$ circle -std=c++17 repro.cpp 
error: repro.cpp:17:12
undeclared identifier '__deduced_true1'
           REQUIRES(std::is_arithmetic<T>::value) 
           ^
```

Compiler details:

```
$ circle --version
circle version 1.0.0-132
  Circle public preview build 132
  Built Sep 20 2021 18:12:19
  (c) 2021 Sean Baxter
  https://www.circle-lang.org/
  Twitter: @seanbax
```

**Comment by seanbaxter** [comment]
Fixed. Will be in build 133.

**Comment by jaredhoberock** [comment]
Thanks for taking a look, but I still see the same behavior in build 133:

```
$ circle repro.cpp
error: repro.cpp:17:12
undeclared identifier '__deduced_true1'
           REQUIRES(std::is_arithmetic<T>::value) 
           ^

$ circle --version
circle version 1.0.0-133
  Circle public preview build 133
  Built Sep 25 2021 00:35:45
  (c) 2021 Sean Baxter
  https://www.circle-lang.org/
  Twitter: @seanbax
```

**Comment by seanbaxter** [comment]
Uhh I don't believe it. I swear I had it last night. Give me a second.

**Comment by seanbaxter** [comment]
Ok now it's REALLY FIXED. Build 134 is uploaded.

**Comment by jaredhoberock** [comment]
Thanks, confirmed.
